### ISSUE TITLE
A function passed as value to a perl sub is converted to hashref.

### ISSUE THREAD

**Issue by cafe01** [gonzus/JavaScript-Duktape-XS#10]
Hi there, first of all, thanks for the great work!

Can you confirm this is a bug or am I missing something?

```
use Test::More;
use JavaScript::Duktape::XS;

my $js = JavaScript::Duktape::XS->new;

$js->set('doSomething', sub {
    my @args = @_;
    is scalar(@args), 6;
    is $args[0], 32;
    is $args[1], 'foo';
    is $args[2], 1;
    
    isa_ok $args[3], 'ARRAY';
    is_deeply $args[3], [3, 4];
    
    isa_ok $args[4], 'HASH';
    is_deeply $args[4], { foo => 'bar' };

    isa_ok $args[5], 'CODE';
});

$js->eval('doSomething(32, "foo", true, [3, 4], { foo: "bar" }, function() {})');

done_testing;
```

**Comment by gonzus** [comment]
Hi @cafe01 . There is no sensible, meaningful interpretation to this code. You are passing a JS function into a Perl sub, and are expecting that the JS function will magically become a coderef. That will never work.

What exactly are you trying to do? Perhaps there is a different approach for this. Cheers.

**Comment by cafe01** [comment]
Hi @gonzus. The use case is when I need to pass a callback/handler to the perl side of my application. 
I have a CMS app (https://github.com/cafe01/k1plaza) where website code runs on a javascript sandbox. 
The javascript app depends heavily on the this callback/handler architecture.

Here is the same test using JavaScript::V8 (the module I'm currently using on cafe01/k1plaza, and desperate to get rid of).

```
use Test::More;
use JavaScript::V8;

my $js = JavaScript::V8::Context->new;

$js->bind('doSomething', sub {
    my @args = @_;
    is scalar(@args), 6;
    is $args[0], 32;
    is $args[1], 'foo';
    is $args[2], 1;
    
    isa_ok $args[3], 'ARRAY';
    is_deeply $args[3], [3, 4];
    
    isa_ok $args[4], 'HASH';
    is_deeply $args[4], { foo => 'bar' };

    isa_ok $args[5], 'CODE';
});

$js->eval('doSomething(32, "foo", true, [3, 4], { foo: "bar" }, function() {})');

done_testing;
```
Thank you for the attention.

**Comment by gonzus** [comment]
I would imagine that from the Perl code you want to execute that JS function you passed as a parameter? If yes, you could consider passing the *name* of the JS function as a string into perl, and have perl call `$vm->eval($my_function_name)`. Of course, you would need to work out how to pass parameters into that handler.

**Comment by cafe01** [comment]
And also where on the javascript context is that function.. since ->eval('myFunc()') assumes myFunc to exist on the global scope, right?

From the js side, the common pattern is to just past in a function, or a  "fat arrow functions" on ES6. 

Here is an exemple of real code I need to run:
```
k1plaza.addRoute("/foo", function(c) {
    c.render('json', { foo: 'bar' })
});
```
Being a user of JavaScript::V8 for a long time, a lot of my code has this features as a requirement, and unless it's a bad idea from the XS point of view (which I don't have knowledge to asses), I would insist that this a very handy feature. 

You are the wizard in charge, if its not a good magic to perform then I'll be forced to redesign a few things here. 

OBS: although my initial test was on JavaScript:::Duktape::XS, my plan is really to migrate to JavaScript::V8::XS. But I'm assuming you are implementing the same API/semantics for both, right?

**Comment by cafe01** [comment]
Ok, I understand. I'll wait for the next versions :)
Are you using JavaScript:::Duktape::XS and/or JavaScript:::V8::XS  on production already?

**Comment by gonzus** [comment]
Yes, we are using both modules in production. And just to be clear, I don't think I will implement what we discussed here. I also think it might be a good idea to restructure your code so that you don't depend on this functionality.

Cheers!

**Comment by cafe01** [comment]
Awesome! Can you elaborate a little bit about the use cases / reasons for when to use one or the other? Why are you using both?

About the js-function to perl-sub thing, I'm already redesigning things to not rely on that.

Cheers!

**Comment by cafe01** [comment]
Yeah, I thought that would be the reasons.
I'm trying to install JavaScript::V8::XS. Managed to compile v8 already, but couldn't make JavaScript::V8::XS install yet.

The compiled v8 files are on a custom path, any advice? I thing its just a matter to point point Makefile.PL to the correct paths, right?

**Comment by gonzus** [comment]
Probably correct. Or, you could just consider installing your built V8 libraries (including libicu) to a "standard place".

**Comment by cafe01** [comment]
I've followed the instructions on https://github.com/v8/v8/wiki/Building-with-GN
The build process generated the output at `v8/out/x64.release/`

Instructions at https://metacpan.org/pod/JavaScript::V8::XS#DEPENDENCIES mention the header files, shared files, v8 blobs and icu data file. 

I can see the v8 blobs and icu data file are at the `v8/out/x64.release/` directory, just don't know where to copy them to. The v8 include files I'm assuming are the `v8/include/` dir. And I don't know where are the shared libraries.

Thank you for the attention. :+1:

**Comment by gonzus** [comment]
The include and library files are compile-time assets, you need to make sure they are available when you are building with `perl Makefile.PL && make test`. I put mine in `/usr/local/{include,lib}`, for example.

The blobs and icu data files are required when you load the V8 library. Function `get_data_path()` in `V8Context.cc` will search for them in several standard places, and when it finds them, it initializes V8 with the found files.

Hope that helps. Cheers.

**Comment by cafe01** [comment]
Yes it helps. I think the build instructions I followed didn't produce shared libs.
Could you mention the filename of some of the required libs so I can find it in my built files?
Thank you. :)

**Comment by gonzus** [comment]
On my mac:
```$ ls -l /usr/local/lib/ | egrep v8
-rwxr-xr-x   1 root       admin    17M Jun 14 10:22 libv8.dylib*
-rwxr-xr-x   1 root       admin    17M Jun 14 10:22 libv8_for_testing.dylib*
-rwxr-xr-x   1 root       admin   162K Jun 14 10:22 libv8_libbase.dylib*
-rwxr-xr-x   1 root       admin   124K Jun 14 10:22 libv8_libplatform.dylib*
```

On linux:
```$ ls -l /usr/lib64/ | egrep v8
lrwxrwxrwx   1 root root       18 Jul  5 14:50 libv8_libbase.so -> libv8_libbase.so.6
-rwxr-xr-x   1 root root  1927312 Jun 27 17:39 libv8_libbase.so.6
lrwxrwxrwx   1 root root       22 Jul  5 14:50 libv8_libplatform.so -> libv8_libplatform.so.6
-rwxr-xr-x   1 root root  1887696 Jun 27 17:39 libv8_libplatform.so.6
lrwxrwxrwx   1 root root       10 Jul  5 14:50 libv8.so -> libv8.so.6
-rwxr-xr-x   1 root root 21966328 Jun 27 17:39 libv8.so.6
```

**Comment by gonzus** [comment]
BTW @cafe01 can I ask you if you can go ahead and close this issue? Thanks!

**Comment by cafe01** [comment]
Yes. Thank you! :)
