### ISSUE TITLE
How to integrate setTimeout() to perl-side event loop.

### ISSUE THREAD

**Issue by cafe01** [gonzus/JavaScript-Duktape-XS#11]
Ive just tested a code that was based on JavaScript::V8 and where I had to provide the setTimeout function from the perl side.

Since JavaScript::Duktape::XS already provides the setTimeout() function, how can I integrate that to an existing perl event loop? 

OBS: I'm assuming that's why my js code that uses setTimeout() is not working.

**Comment by gonzus** [comment]
Unfortunately, the `setTimeout` implementation is very simple minded and doesn't have any points of integration with an event loop. The only reason it is there, is because we needed to make sure we could dispatch a function inside a `setTimeout` and wait for all handlers to be called.

**Comment by cafe01** [comment]
I understand. What about the setTimeout on JavaScript::V8::XS? Is there a way to integrate it to an event loop?

As I've mentioned, on JavaScript::V8 I can provide integrate the setTimeout to an event loop, but it relies on the fact that a JS function is converter to a perl coderef when passed as argumento a perl function. (what we discussed on the other issue)

Thank you for the attention. :)

**Comment by gonzus** [comment]
The V8 `setTimeout` implementation is actually a copy of the Duktape one... So, same limitations apply.

**Comment by gonzus** [comment]
BTW: I am a JS ignoramus. So if there is a standard / recommended / well known way of doing this, I would appreciate any suggestions, even if they mean we have to change the way we implement `setTimeout` today.

In the meantime, if there are no specific suggestions, I would ask you to close this issue if possible. Thanks!

**Comment by cafe01** [comment]
Ok. Thank you!
