### ISSUE TITLE
Throw exception inside module_resolver

### ISSUE THREAD

**Issue by gflohr** [gonzus/JavaScript-Duktape-XS#13]
I have this resolver:

```perl
use JavaScript::Duktape::XS;

my $vm = JavaScript::Duktape::XS->new;
$vm->set(perl_module_resolve => sub { die "not found" });
$vm->eval("require('whatever')");
```

Output:

```
error: TypeError: string required, found null (stack index -1)
    at [anon] (duk_api_stack.c:2101) internal
    at require () native strict preventsyield
    at global (input:1) preventsyield
```

I was expecting to see the actual exception "not found". Any way to get that done?

**Comment by gonzus** [comment]
You are right. I fixed this with 26ac2e9047afa9d7a20f9e76d907a9cf6e07175a and added tests in the same commit. Thanks!

**Comment by gflohr** [comment]
Cool, thanks. It works for me with the current version from git.

Maybe, from the end user's perspective, a slightly different wording would be helpful, something like "Module resolver died with error: %s\n". The error message is the result of the end user having run a Perl program. The context "Perl sub" is then a little bit confusing, isn't it?

**Comment by gonzus** [comment]
Maybe, but that code handles all call to perl subs, so I opted for a generic error message. If you want, you could surface the error to the caller and print out a more specific message; patches welcome!

**Comment by gflohr** [comment]
I thought it was specific for the module resolver. Then ignore my comment. I can always generate a more specific exception in the Perl code

By the way, https://github.com/gflohr/qgoda/blob/master/lib/Qgoda/JavaScript/Environment.pm contains a complete and working example for a module resolver à la Node.JS.

**Comment by gflohr** [comment]
There is a problem with that commit. You can not catch resolver errors from JavaScript:

```javascript
try {
    require('does-not-exist');
}
catch(e) {
    console.log("doesn't matter");
}
```

Running that code with `eval()` will always die with the exception "Perl sub died with error: ..." because the catch block is never exected. I think that behavior is not specific to my project.

**Comment by gonzus** [comment]
Yes, that is correct. This is a bit of a design question: should a die in Perl actually die (current fixed behaviour)? Should it capture the error and bubble it up to JS? As a JS exception or something else?

I am open to ideas / suggestions / patches.

**Comment by gflohr** [comment]
I have edited my last comment and made the example self-containing.

I think the Perl exception should bubble up as a JavaScript exception. Otherwise the engine no longer behaves correctly because `catch` should catch every kind of error except for problems in the engine itself like segfaults, out of memory and so on.

It would be okay if there was another way to report an error but https://github.com/svaarala/duktape/tree/master/extras/module-node explicitely says "throw an error" from the resolve/load callback.

I had also tried to print a warning to `stderr` before dying in the module resolver. But that causes cosmetic problems, when JavaScript code actually expects failure, like for example in https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/binary.js at the top of the file. You then always see the ugly "Cannot find module 'buffer'" on the console, whenever the code is executed, although the error is handled gracefully.

The problem is not so urgent for me. My code is supported to work without exceptions, so I could also live with the original version but I think that this issue makes the possibility to call Perl from JavaScript less useful then it could be.

**Comment by gonzus** [comment]
I agree with your analysis. This bit of code is a bit complex, so it will take me a while to change it to capture the Perl exception and re-raise it as a JS exception. Will let you know here once it is done.

**Comment by gflohr** [comment]
No worries. For qgoda I can ensure that `require()` will not fail where it shouldn't fail. Take your time.

**Comment by gflohr** [comment]
Any news on this?

For [Qgoda](https://github.com/gflohr/qgoda) I have to force users to downgrade their `JavaScript::Duktape::XS` to 0.000074 because every newer version breaks the software and the error is uncatchable.

Would it be an option to restore the behavior 0.000074 for the time being?

**Comment by gonzus** [comment]
Hey! Apologies, I have not had time to look at this, and may not have a lot of time in the near future. If you want to work on a patch, I would gladly consider merging it once it is in good shape.

**Comment by gflohr** [comment]
I did already look into it but I'm afraid, I don't understand the code good enough for a patch. But I will try again next weekend.

Anyway, what about restoring the old behavior of 0.000074 which at least allowed for workarounds?

**Comment by gonzus** [comment]
One quick thing I can think of is adding an option to the `JavaScript::Duktape::XS->new` method, to select whether a Perl error during a callback from JS should `croak` (new, default behaviour) or do nothing (previous behaviour).

It should certainly be possible to convert the Perl error into a JS exception, but I don't have the time to write this myself right now. If / when this is added, this could be a third (eventually default) value for this setting. What do you think?

**Comment by gflohr** [comment]
That would be very helpful. Thanks!

**Comment by gflohr** [comment]
I think with PR https://github.com/gonzus/JavaScript-Duktape-XS/pull/34 the ball is in your half, isn't it? ;) Any chance that you can incorporate the solution?

**Comment by gonzus** [comment]
Done, thanks for your contribution!
