### ISSUE TITLE
How to return from `eval()`

### ISSUE THREAD

**Issue by gflohr** [gonzus/JavaScript-Duktape-XS#15]
Sorry for spamming you with issues ...

The documentation for `eval()` says 'Any returned values will be treated in the same way as a call to "get"'. But how can I actually return a value from the code?

I am currently using a global JavaScript object `__perl__` for communicating input and output variables between JavaScript and Perl. Is there a smarter way to do this by "returning" something from the JavaScript code?

**Comment by gonzus** [comment]
I am not sure I understood you correctly; this works for me:
```perl
use JavaScript::Duktape::XS;
my $vm = JavaScript::Duktape::XS->new();
my $x = $vm->eval("var a = 4; var b = 3; a + b;");
say $x;
```
And it prints 7.

**Comment by gflohr** [comment]
So, the return value is simply the value of the last expression?

I didn't try that out because JavaScript normally requires an explicit `return`. But it's clear now. Thanks!
