### ISSUE TITLE
Add `typeof` method to check type of JS variables

### ISSUE THREAD

**Issue by stevan** [gonzus/JavaScript-Duktape-XS#2]
I would like to be able to introspect the types of objects within the JS runtime environment, the simplest approach I can think of is to use the JS `typeof` operator (which I assume Duktape supports) and then just return this. 

I might try and write a patch myself, but here is the issue just in case you would like to discuss details.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

**Comment by stevan** [comment]
I was unable to find the parts of the API that would give me the `typeof` behavior, but I think the Perl side API should be something like:
```
my $type = $duk->typeof('global.some.number');
```
And then, assuming that `global.some.number` is a `Number` object in the Duktape runtime, then `$type` will contain the string "number".

**Comment by gonzus** [comment]
Done with eaddc69af56d1fac680f8492fe45c99d6e08b297

I am not sure how to deal with boolean objects... In the sense that, we cannot pass booleans from Perl, since Perl has no such concept.

**Comment by gonzus** [comment]
Of course, the answer was to have a specific test for booleans, which I have done with 8bf999463d5fc615e2145d32490311ba8259c8e1. All is well now.
