### ISSUE TITLE
Add `clear` method to clear a JS variable 

### ISSUE THREAD

**Issue by stevan** [gonzus/JavaScript-Duktape-XS#6]
It would be useful to be able to clear a JS variable from the Perl side without needing to set it to `undef` or something similar. This would be useful for resetting global variables and such.

I would assume that the variable would be set to `undefined` in the JS sense of the word and any Duktape objects previously stored in the variable would be deleted and memory deallocated as is sensible.

**Comment by gonzus** [comment]
@stevan if I understand, you would like to be able to call `$duk->clear('myVariable")` and have that internally set it to `undef`, right? So, no visible difference from calling `$duk->set('myVariable', undef)`, correct?

**Comment by gonzus** [comment]
In the end, I decided that the `$duk->clear('myVariable')` method actually obfuscates what you are doing, and it is clearer (pun intended) to call `$duk->set('myVariable', undef)`. So, closing this issue.
