### ISSUE TITLE
Add `instanceof` method to check type of JS variables

### ISSUE THREAD

**Issue by stevan** [gonzus/JavaScript-Duktape-XS#7]
Similarly to the `typeof` operator (#2 ) it would be good to be able to test what something is an instance of as well. 

The Perl API might look something like this:
```
my $bool = $duk->instanceof('some.instance.of.foo', 'the.constuctor.for.Foo');
```
Which would be the equivalent to the following in JS:
```
var bool = some.instance.of.foo instanceof the.constructor.for.Foo;
```

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by gonzus** [comment]
Done with 63336d126dfda10fdbb3bd3b455c0d3ee06a0a59.
