### ISSUE TITLE
Add support for Node.js-like module loading framework

### ISSUE THREAD

**Issue by stevan** [gonzus/JavaScript-Duktape-XS#8]
This is an "extra" in duktape and requires a few C functions to be implemented for resolving and loading the code, but otherwise looks pretty straightforward. 

https://github.com/svaarala/duktape/tree/master/extras/module-node

**Comment by gonzus** [comment]
I am working on this. The plan is to allow passing two Perl subs for the actual implementation of resolve and load, so that this is totally configurable by the caller.
